// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/archive.dart';
import 'api/bridge.dart';
import 'api/dedupe.dart';
import 'api/fileops.dart';
import 'api/listing.dart';
import 'api/quick.dart';
import 'api/search.dart';
import 'api/thumbnail.dart';
import 'api/trash.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class NotilusCore extends BaseEntrypoint<NotilusCoreApi, NotilusCoreApiImpl,
    NotilusCoreWire> {
  @internal
  static final instance = NotilusCore._();

  NotilusCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    NotilusCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required NotilusCoreApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<NotilusCoreApiImpl, NotilusCoreWire>
      get apiImplConstructor => NotilusCoreApiImpl.new;

  @override
  WireConstructor<NotilusCoreWire> get wireConstructor =>
      NotilusCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiBridgeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -545290107;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'notilus_core',
    ioDirectory: 'core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class NotilusCoreApi extends BaseApi {
  Future<bool> crateApiBridgeCancelOp({required String opId});

  Stream<QuickEvent> crateApiBridgeCompressPathsStream(
      {required List<String> sources,
      required String destDir,
      required String archiveName,
      required String opId});

  Future<String> crateApiBridgeConvertImage(
      {required String src,
      required String destDir,
      required ImageTarget format,
      int? maxDim,
      required int quality});

  Stream<OpEvent> crateApiBridgeCopyPathsStream(
      {required List<String> sources,
      required String destDir,
      required Collision collision,
      required String opId});

  Future<String> crateApiBridgeCreateDir(
      {required String dir, required String name});

  Future<String> crateApiBridgeCreateFile(
      {required String dir, required String name});

  Future<TrashOutcome> crateApiBridgeDeletePermanently(
      {required List<String> paths});

  Future<Uint8List> crateApiBridgeExtractArchiveEntry(
      {required String path, required String entryName});

  Stream<QuickEvent> crateApiBridgeExtractArchiveStream(
      {required String path,
      required String destDir,
      required bool intoSubfolder,
      required String opId});

  Stream<StatsEvent> crateApiBridgeFolderStatsStream(
      {required String path, required String opId});

  Future<String> crateApiBridgeHashFile({required String path});

  Future<String> crateApiBridgeHashFilePrefix(
      {required String path, required BigInt window});

  Future<void> crateApiBridgeInitApp();

  Future<List<ArchiveEntry>> crateApiBridgeListArchive({required String path});

  Future<List<DirEntryInfo>> crateApiBridgeListDir(
      {required String path, required SortSpec sort});

  Future<Uint64List> crateApiBridgeMeasurePaths({required List<String> paths});

  Stream<OpEvent> crateApiBridgeMovePathsStream(
      {required List<String> sources,
      required String destDir,
      required Collision collision,
      required String opId});

  Future<TrashOutcome> crateApiBridgeMoveToTrash({required List<String> paths});

  Future<String> crateApiBridgeRenamePath(
      {required String path, required String newName});

  Stream<ScanEvent> crateApiBridgeScanDuplicatesStream(
      {required ScanRequest req, required String opId});

  Stream<SearchEvent> crateApiBridgeSearchFilesStream(
      {required SearchRequest req, required String opId});

  Future<String> crateApiBridgeThumbnailCacheKey(
      {required String path,
      required PlatformInt64 modifiedMs,
      required BigInt size,
      required int dim});

  Future<ThumbnailInfo> crateApiBridgeThumbnailImage(
      {required String src, required String dst, required int maxDim});

  Future<String> crateApiBridgeTransformImage(
      {required String src,
      required ImageTransform transform,
      required bool inPlace});
}

class NotilusCoreApiImpl extends NotilusCoreApiImplPlatform
    implements NotilusCoreApi {
  NotilusCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiBridgeCancelOp({required String opId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(opId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBridgeCancelOpConstMeta,
      argValues: [opId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeCancelOpConstMeta => const TaskConstMeta(
        debugName: "cancel_op",
        argNames: ["opId"],
      );

  @override
  Stream<QuickEvent> crateApiBridgeCompressPathsStream(
      {required List<String> sources,
      required String destDir,
      required String archiveName,
      required String opId}) {
    final sink = RustStreamSink<QuickEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(sources, serializer);
        sse_encode_String(destDir, serializer);
        sse_encode_String(archiveName, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_quick_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeCompressPathsStreamConstMeta,
      argValues: [sources, destDir, archiveName, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeCompressPathsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "compress_paths_stream",
        argNames: ["sources", "destDir", "archiveName", "opId", "sink"],
      );

  @override
  Future<String> crateApiBridgeConvertImage(
      {required String src,
      required String destDir,
      required ImageTarget format,
      int? maxDim,
      required int quality}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(src, serializer);
        sse_encode_String(destDir, serializer);
        sse_encode_image_target(format, serializer);
        sse_encode_opt_box_autoadd_u_32(maxDim, serializer);
        sse_encode_u_8(quality, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeConvertImageConstMeta,
      argValues: [src, destDir, format, maxDim, quality],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeConvertImageConstMeta => const TaskConstMeta(
        debugName: "convert_image",
        argNames: ["src", "destDir", "format", "maxDim", "quality"],
      );

  @override
  Stream<OpEvent> crateApiBridgeCopyPathsStream(
      {required List<String> sources,
      required String destDir,
      required Collision collision,
      required String opId}) {
    final sink = RustStreamSink<OpEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(sources, serializer);
        sse_encode_String(destDir, serializer);
        sse_encode_collision(collision, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_op_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeCopyPathsStreamConstMeta,
      argValues: [sources, destDir, collision, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeCopyPathsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "copy_paths_stream",
        argNames: ["sources", "destDir", "collision", "opId", "sink"],
      );

  @override
  Future<String> crateApiBridgeCreateDir(
      {required String dir, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeCreateDirConstMeta,
      argValues: [dir, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeCreateDirConstMeta => const TaskConstMeta(
        debugName: "create_dir",
        argNames: ["dir", "name"],
      );

  @override
  Future<String> crateApiBridgeCreateFile(
      {required String dir, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeCreateFileConstMeta,
      argValues: [dir, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeCreateFileConstMeta => const TaskConstMeta(
        debugName: "create_file",
        argNames: ["dir", "name"],
      );

  @override
  Future<TrashOutcome> crateApiBridgeDeletePermanently(
      {required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_trash_outcome,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBridgeDeletePermanentlyConstMeta,
      argValues: [paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeDeletePermanentlyConstMeta =>
      const TaskConstMeta(
        debugName: "delete_permanently",
        argNames: ["paths"],
      );

  @override
  Future<Uint8List> crateApiBridgeExtractArchiveEntry(
      {required String path, required String entryName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(entryName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeExtractArchiveEntryConstMeta,
      argValues: [path, entryName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeExtractArchiveEntryConstMeta =>
      const TaskConstMeta(
        debugName: "extract_archive_entry",
        argNames: ["path", "entryName"],
      );

  @override
  Stream<QuickEvent> crateApiBridgeExtractArchiveStream(
      {required String path,
      required String destDir,
      required bool intoSubfolder,
      required String opId}) {
    final sink = RustStreamSink<QuickEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(destDir, serializer);
        sse_encode_bool(intoSubfolder, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_quick_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeExtractArchiveStreamConstMeta,
      argValues: [path, destDir, intoSubfolder, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeExtractArchiveStreamConstMeta =>
      const TaskConstMeta(
        debugName: "extract_archive_stream",
        argNames: ["path", "destDir", "intoSubfolder", "opId", "sink"],
      );

  @override
  Stream<StatsEvent> crateApiBridgeFolderStatsStream(
      {required String path, required String opId}) {
    final sink = RustStreamSink<StatsEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_stats_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeFolderStatsStreamConstMeta,
      argValues: [path, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeFolderStatsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "folder_stats_stream",
        argNames: ["path", "opId", "sink"],
      );

  @override
  Future<String> crateApiBridgeHashFile({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeHashFileConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeHashFileConstMeta => const TaskConstMeta(
        debugName: "hash_file",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiBridgeHashFilePrefix(
      {required String path, required BigInt window}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_64(window, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeHashFilePrefixConstMeta,
      argValues: [path, window],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeHashFilePrefixConstMeta =>
      const TaskConstMeta(
        debugName: "hash_file_prefix",
        argNames: ["path", "window"],
      );

  @override
  Future<void> crateApiBridgeInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBridgeInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<List<ArchiveEntry>> crateApiBridgeListArchive({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_archive_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeListArchiveConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeListArchiveConstMeta => const TaskConstMeta(
        debugName: "list_archive",
        argNames: ["path"],
      );

  @override
  Future<List<DirEntryInfo>> crateApiBridgeListDir(
      {required String path, required SortSpec sort}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_sort_spec(sort, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dir_entry_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeListDirConstMeta,
      argValues: [path, sort],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeListDirConstMeta => const TaskConstMeta(
        debugName: "list_dir",
        argNames: ["path", "sort"],
      );

  @override
  Future<Uint64List> crateApiBridgeMeasurePaths({required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_64_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBridgeMeasurePathsConstMeta,
      argValues: [paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeMeasurePathsConstMeta => const TaskConstMeta(
        debugName: "measure_paths",
        argNames: ["paths"],
      );

  @override
  Stream<OpEvent> crateApiBridgeMovePathsStream(
      {required List<String> sources,
      required String destDir,
      required Collision collision,
      required String opId}) {
    final sink = RustStreamSink<OpEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(sources, serializer);
        sse_encode_String(destDir, serializer);
        sse_encode_collision(collision, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_op_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeMovePathsStreamConstMeta,
      argValues: [sources, destDir, collision, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeMovePathsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "move_paths_stream",
        argNames: ["sources", "destDir", "collision", "opId", "sink"],
      );

  @override
  Future<TrashOutcome> crateApiBridgeMoveToTrash(
      {required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_trash_outcome,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBridgeMoveToTrashConstMeta,
      argValues: [paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeMoveToTrashConstMeta => const TaskConstMeta(
        debugName: "move_to_trash",
        argNames: ["paths"],
      );

  @override
  Future<String> crateApiBridgeRenamePath(
      {required String path, required String newName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(newName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeRenamePathConstMeta,
      argValues: [path, newName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeRenamePathConstMeta => const TaskConstMeta(
        debugName: "rename_path",
        argNames: ["path", "newName"],
      );

  @override
  Stream<ScanEvent> crateApiBridgeScanDuplicatesStream(
      {required ScanRequest req, required String opId}) {
    final sink = RustStreamSink<ScanEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_scan_request(req, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_scan_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeScanDuplicatesStreamConstMeta,
      argValues: [req, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeScanDuplicatesStreamConstMeta =>
      const TaskConstMeta(
        debugName: "scan_duplicates_stream",
        argNames: ["req", "opId", "sink"],
      );

  @override
  Stream<SearchEvent> crateApiBridgeSearchFilesStream(
      {required SearchRequest req, required String opId}) {
    final sink = RustStreamSink<SearchEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_search_request(req, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_StreamSink_search_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeSearchFilesStreamConstMeta,
      argValues: [req, opId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiBridgeSearchFilesStreamConstMeta =>
      const TaskConstMeta(
        debugName: "search_files_stream",
        argNames: ["req", "opId", "sink"],
      );

  @override
  Future<String> crateApiBridgeThumbnailCacheKey(
      {required String path,
      required PlatformInt64 modifiedMs,
      required BigInt size,
      required int dim}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_i_64(modifiedMs, serializer);
        sse_encode_u_64(size, serializer);
        sse_encode_u_32(dim, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiBridgeThumbnailCacheKeyConstMeta,
      argValues: [path, modifiedMs, size, dim],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeThumbnailCacheKeyConstMeta =>
      const TaskConstMeta(
        debugName: "thumbnail_cache_key",
        argNames: ["path", "modifiedMs", "size", "dim"],
      );

  @override
  Future<ThumbnailInfo> crateApiBridgeThumbnailImage(
      {required String src, required String dst, required int maxDim}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(src, serializer);
        sse_encode_String(dst, serializer);
        sse_encode_u_32(maxDim, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_thumbnail_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeThumbnailImageConstMeta,
      argValues: [src, dst, maxDim],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeThumbnailImageConstMeta =>
      const TaskConstMeta(
        debugName: "thumbnail_image",
        argNames: ["src", "dst", "maxDim"],
      );

  @override
  Future<String> crateApiBridgeTransformImage(
      {required String src,
      required ImageTransform transform,
      required bool inPlace}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(src, serializer);
        sse_encode_image_transform(transform, serializer);
        sse_encode_bool(inPlace, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiBridgeTransformImageConstMeta,
      argValues: [src, transform, inPlace],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBridgeTransformImageConstMeta =>
      const TaskConstMeta(
        debugName: "transform_image",
        argNames: ["src", "transform", "inPlace"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<OpEvent> dco_decode_StreamSink_op_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<QuickEvent> dco_decode_StreamSink_quick_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ScanEvent> dco_decode_StreamSink_scan_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SearchEvent> dco_decode_StreamSink_search_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<StatsEvent> dco_decode_StreamSink_stats_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ArchiveEntry dco_decode_archive_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ArchiveEntry(
      name: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
      isDir: dco_decode_bool(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FolderStats dco_decode_box_autoadd_folder_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_folder_stats(raw);
  }

  @protected
  OpOutcome dco_decode_box_autoadd_op_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_op_outcome(raw);
  }

  @protected
  OpProgress dco_decode_box_autoadd_op_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_op_progress(raw);
  }

  @protected
  QuickOutcome dco_decode_box_autoadd_quick_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_quick_outcome(raw);
  }

  @protected
  QuickProgress dco_decode_box_autoadd_quick_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_quick_progress(raw);
  }

  @protected
  ScanProgress dco_decode_box_autoadd_scan_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scan_progress(raw);
  }

  @protected
  ScanRequest dco_decode_box_autoadd_scan_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scan_request(raw);
  }

  @protected
  SearchHit dco_decode_box_autoadd_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_hit(raw);
  }

  @protected
  SearchRequest dco_decode_box_autoadd_search_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_request(raw);
  }

  @protected
  SearchSummary dco_decode_box_autoadd_search_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_search_summary(raw);
  }

  @protected
  SortSpec dco_decode_box_autoadd_sort_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sort_spec(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  Collision dco_decode_collision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Collision.values[raw as int];
  }

  @protected
  DirEntryInfo dco_decode_dir_entry_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DirEntryInfo(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isDir: dco_decode_bool(arr[2]),
      size: dco_decode_u_64(arr[3]),
      modifiedMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  DuplicateGroup dco_decode_duplicate_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DuplicateGroup(
      hash: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
      files: dco_decode_list_dir_entry_info(arr[2]),
    );
  }

  @protected
  FailedItem dco_decode_failed_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FailedItem(
      path: dco_decode_String(arr[0]),
      error: dco_decode_String(arr[1]),
    );
  }

  @protected
  FolderStats dco_decode_folder_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return FolderStats(
      path: dco_decode_String(arr[0]),
      files: dco_decode_u_64(arr[1]),
      dirs: dco_decode_u_64(arr[2]),
      bytes: dco_decode_u_64(arr[3]),
      largestPath: dco_decode_String(arr[4]),
      largestBytes: dco_decode_u_64(arr[5]),
      newestMs: dco_decode_i_64(arr[6]),
      unreadable: dco_decode_u_64(arr[7]),
      cancelled: dco_decode_bool(arr[8]),
    );
  }

  @protected
  HitKind dco_decode_hit_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HitKind.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImageTarget dco_decode_image_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImageTarget.values[raw as int];
  }

  @protected
  ImageTransform dco_decode_image_transform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImageTransform.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ArchiveEntry> dco_decode_list_archive_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_archive_entry).toList();
  }

  @protected
  List<DirEntryInfo> dco_decode_list_dir_entry_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dir_entry_info).toList();
  }

  @protected
  List<DuplicateGroup> dco_decode_list_duplicate_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_duplicate_group).toList();
  }

  @protected
  List<FailedItem> dco_decode_list_failed_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_failed_item).toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit).toList();
  }

  @protected
  OpEvent dco_decode_op_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return OpEvent_Progress(
          dco_decode_box_autoadd_op_progress(raw[1]),
        );
      case 1:
        return OpEvent_Done(
          dco_decode_box_autoadd_op_outcome(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  OpOutcome dco_decode_op_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OpOutcome(
      completed: dco_decode_list_String(arr[0]),
      skipped: dco_decode_list_String(arr[1]),
      failed: dco_decode_list_failed_item(arr[2]),
      cancelled: dco_decode_bool(arr[3]),
    );
  }

  @protected
  OpProgress dco_decode_op_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OpProgress(
      filesDone: dco_decode_u_64(arr[0]),
      filesTotal: dco_decode_u_64(arr[1]),
      bytesDone: dco_decode_u_64(arr[2]),
      bytesTotal: dco_decode_u_64(arr[3]),
      current: dco_decode_String(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  QuickEvent dco_decode_quick_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return QuickEvent_Progress(
          dco_decode_box_autoadd_quick_progress(raw[1]),
        );
      case 1:
        return QuickEvent_Done(
          dco_decode_box_autoadd_quick_outcome(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  QuickOutcome dco_decode_quick_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QuickOutcome(
      produced: dco_decode_list_String(arr[0]),
      failed: dco_decode_list_failed_item(arr[1]),
      cancelled: dco_decode_bool(arr[2]),
    );
  }

  @protected
  QuickProgress dco_decode_quick_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QuickProgress(
      filesDone: dco_decode_u_64(arr[0]),
      filesTotal: dco_decode_u_64(arr[1]),
      bytesDone: dco_decode_u_64(arr[2]),
      bytesTotal: dco_decode_u_64(arr[3]),
      current: dco_decode_String(arr[4]),
    );
  }

  @protected
  ScanEvent dco_decode_scan_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ScanEvent_Progress(
          dco_decode_box_autoadd_scan_progress(raw[1]),
        );
      case 1:
        return ScanEvent_Done(
          dco_decode_list_duplicate_group(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ScanPhase dco_decode_scan_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScanPhase.values[raw as int];
  }

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ScanProgress(
      phase: dco_decode_scan_phase(arr[0]),
      filesSeen: dco_decode_u_64(arr[1]),
      filesHashed: dco_decode_u_64(arr[2]),
      hashTotal: dco_decode_u_64(arr[3]),
      currentPath: dco_decode_String(arr[4]),
    );
  }

  @protected
  ScanRequest dco_decode_scan_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ScanRequest(
      roots: dco_decode_list_String(arr[0]),
      minSize: dco_decode_u_64(arr[1]),
      excludedDirNames: dco_decode_list_String(arr[2]),
      allowedExtensions: dco_decode_opt_list_String(arr[3]),
      skipHidden: dco_decode_bool(arr[4]),
      skipBundles: dco_decode_bool(arr[5]),
    );
  }

  @protected
  SearchEvent dco_decode_search_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SearchEvent_Hit(
          dco_decode_box_autoadd_search_hit(raw[1]),
        );
      case 1:
        return SearchEvent_Done(
          dco_decode_box_autoadd_search_summary(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  SearchHit dco_decode_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchHit(
      entry: dco_decode_dir_entry_info(arr[0]),
      kind: dco_decode_hit_kind(arr[1]),
      line: dco_decode_opt_box_autoadd_u_64(arr[2]),
      preview: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  SearchRequest dco_decode_search_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SearchRequest(
      roots: dco_decode_list_String(arr[0]),
      query: dco_decode_String(arr[1]),
      searchContent: dco_decode_bool(arr[2]),
      matchCase: dco_decode_bool(arr[3]),
      useWildcards: dco_decode_bool(arr[4]),
      maxResults: dco_decode_u_64(arr[5]),
      skipHidden: dco_decode_bool(arr[6]),
      excludedDirNames: dco_decode_list_String(arr[7]),
      allowedExtensions: dco_decode_opt_list_String(arr[8]),
    );
  }

  @protected
  SearchSummary dco_decode_search_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchSummary(
      hits: dco_decode_list_search_hit(arr[0]),
      filesScanned: dco_decode_u_64(arr[1]),
      truncated: dco_decode_bool(arr[2]),
      cancelled: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SortField dco_decode_sort_field(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortField.values[raw as int];
  }

  @protected
  SortSpec dco_decode_sort_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SortSpec(
      field: dco_decode_sort_field(arr[0]),
      ascending: dco_decode_bool(arr[1]),
      dirsFirst: dco_decode_bool(arr[2]),
      includeHidden: dco_decode_bool(arr[3]),
    );
  }

  @protected
  StatsEvent dco_decode_stats_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StatsEvent_Progress(
          dco_decode_box_autoadd_quick_progress(raw[1]),
        );
      case 1:
        return StatsEvent_Done(
          dco_decode_box_autoadd_folder_stats(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ThumbnailInfo dco_decode_thumbnail_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ThumbnailInfo(
      path: dco_decode_String(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      fromCache: dco_decode_bool(arr[3]),
    );
  }

  @protected
  TrashOutcome dco_decode_trash_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TrashOutcome(
      trashed: dco_decode_list_String(arr[0]),
      failed: dco_decode_list_failed_item(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<OpEvent> sse_decode_StreamSink_op_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<QuickEvent> sse_decode_StreamSink_quick_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ScanEvent> sse_decode_StreamSink_scan_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SearchEvent> sse_decode_StreamSink_search_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<StatsEvent> sse_decode_StreamSink_stats_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ArchiveEntry sse_decode_archive_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    return ArchiveEntry(name: var_name, size: var_size, isDir: var_isDir);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FolderStats sse_decode_box_autoadd_folder_stats(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_folder_stats(deserializer));
  }

  @protected
  OpOutcome sse_decode_box_autoadd_op_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_op_outcome(deserializer));
  }

  @protected
  OpProgress sse_decode_box_autoadd_op_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_op_progress(deserializer));
  }

  @protected
  QuickOutcome sse_decode_box_autoadd_quick_outcome(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_quick_outcome(deserializer));
  }

  @protected
  QuickProgress sse_decode_box_autoadd_quick_progress(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_quick_progress(deserializer));
  }

  @protected
  ScanProgress sse_decode_box_autoadd_scan_progress(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scan_progress(deserializer));
  }

  @protected
  ScanRequest sse_decode_box_autoadd_scan_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scan_request(deserializer));
  }

  @protected
  SearchHit sse_decode_box_autoadd_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_hit(deserializer));
  }

  @protected
  SearchRequest sse_decode_box_autoadd_search_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_request(deserializer));
  }

  @protected
  SearchSummary sse_decode_box_autoadd_search_summary(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_search_summary(deserializer));
  }

  @protected
  SortSpec sse_decode_box_autoadd_sort_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sort_spec(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  Collision sse_decode_collision(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Collision.values[inner];
  }

  @protected
  DirEntryInfo sse_decode_dir_entry_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modifiedMs = sse_decode_i_64(deserializer);
    return DirEntryInfo(
        path: var_path,
        name: var_name,
        isDir: var_isDir,
        size: var_size,
        modifiedMs: var_modifiedMs);
  }

  @protected
  DuplicateGroup sse_decode_duplicate_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_files = sse_decode_list_dir_entry_info(deserializer);
    return DuplicateGroup(hash: var_hash, size: var_size, files: var_files);
  }

  @protected
  FailedItem sse_decode_failed_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_error = sse_decode_String(deserializer);
    return FailedItem(path: var_path, error: var_error);
  }

  @protected
  FolderStats sse_decode_folder_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_files = sse_decode_u_64(deserializer);
    var var_dirs = sse_decode_u_64(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    var var_largestPath = sse_decode_String(deserializer);
    var var_largestBytes = sse_decode_u_64(deserializer);
    var var_newestMs = sse_decode_i_64(deserializer);
    var var_unreadable = sse_decode_u_64(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return FolderStats(
        path: var_path,
        files: var_files,
        dirs: var_dirs,
        bytes: var_bytes,
        largestPath: var_largestPath,
        largestBytes: var_largestBytes,
        newestMs: var_newestMs,
        unreadable: var_unreadable,
        cancelled: var_cancelled);
  }

  @protected
  HitKind sse_decode_hit_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return HitKind.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImageTarget sse_decode_image_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImageTarget.values[inner];
  }

  @protected
  ImageTransform sse_decode_image_transform(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImageTransform.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArchiveEntry> sse_decode_list_archive_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArchiveEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_archive_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<DirEntryInfo> sse_decode_list_dir_entry_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DirEntryInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dir_entry_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<DuplicateGroup> sse_decode_list_duplicate_group(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DuplicateGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_duplicate_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<FailedItem> sse_decode_list_failed_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FailedItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_failed_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit(deserializer));
    }
    return ans_;
  }

  @protected
  OpEvent sse_decode_op_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_op_progress(deserializer);
        return OpEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_op_outcome(deserializer);
        return OpEvent_Done(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  OpOutcome sse_decode_op_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_completed = sse_decode_list_String(deserializer);
    var var_skipped = sse_decode_list_String(deserializer);
    var var_failed = sse_decode_list_failed_item(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return OpOutcome(
        completed: var_completed,
        skipped: var_skipped,
        failed: var_failed,
        cancelled: var_cancelled);
  }

  @protected
  OpProgress sse_decode_op_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filesDone = sse_decode_u_64(deserializer);
    var var_filesTotal = sse_decode_u_64(deserializer);
    var var_bytesDone = sse_decode_u_64(deserializer);
    var var_bytesTotal = sse_decode_u_64(deserializer);
    var var_current = sse_decode_String(deserializer);
    return OpProgress(
        filesDone: var_filesDone,
        filesTotal: var_filesTotal,
        bytesDone: var_bytesDone,
        bytesTotal: var_bytesTotal,
        current: var_current);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QuickEvent sse_decode_quick_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_quick_progress(deserializer);
        return QuickEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_quick_outcome(deserializer);
        return QuickEvent_Done(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  QuickOutcome sse_decode_quick_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_produced = sse_decode_list_String(deserializer);
    var var_failed = sse_decode_list_failed_item(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return QuickOutcome(
        produced: var_produced, failed: var_failed, cancelled: var_cancelled);
  }

  @protected
  QuickProgress sse_decode_quick_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filesDone = sse_decode_u_64(deserializer);
    var var_filesTotal = sse_decode_u_64(deserializer);
    var var_bytesDone = sse_decode_u_64(deserializer);
    var var_bytesTotal = sse_decode_u_64(deserializer);
    var var_current = sse_decode_String(deserializer);
    return QuickProgress(
        filesDone: var_filesDone,
        filesTotal: var_filesTotal,
        bytesDone: var_bytesDone,
        bytesTotal: var_bytesTotal,
        current: var_current);
  }

  @protected
  ScanEvent sse_decode_scan_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_scan_progress(deserializer);
        return ScanEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_list_duplicate_group(deserializer);
        return ScanEvent_Done(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ScanPhase sse_decode_scan_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ScanPhase.values[inner];
  }

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_scan_phase(deserializer);
    var var_filesSeen = sse_decode_u_64(deserializer);
    var var_filesHashed = sse_decode_u_64(deserializer);
    var var_hashTotal = sse_decode_u_64(deserializer);
    var var_currentPath = sse_decode_String(deserializer);
    return ScanProgress(
        phase: var_phase,
        filesSeen: var_filesSeen,
        filesHashed: var_filesHashed,
        hashTotal: var_hashTotal,
        currentPath: var_currentPath);
  }

  @protected
  ScanRequest sse_decode_scan_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roots = sse_decode_list_String(deserializer);
    var var_minSize = sse_decode_u_64(deserializer);
    var var_excludedDirNames = sse_decode_list_String(deserializer);
    var var_allowedExtensions = sse_decode_opt_list_String(deserializer);
    var var_skipHidden = sse_decode_bool(deserializer);
    var var_skipBundles = sse_decode_bool(deserializer);
    return ScanRequest(
        roots: var_roots,
        minSize: var_minSize,
        excludedDirNames: var_excludedDirNames,
        allowedExtensions: var_allowedExtensions,
        skipHidden: var_skipHidden,
        skipBundles: var_skipBundles);
  }

  @protected
  SearchEvent sse_decode_search_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_search_hit(deserializer);
        return SearchEvent_Hit(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_search_summary(deserializer);
        return SearchEvent_Done(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entry = sse_decode_dir_entry_info(deserializer);
    var var_kind = sse_decode_hit_kind(deserializer);
    var var_line = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_preview = sse_decode_opt_String(deserializer);
    return SearchHit(
        entry: var_entry, kind: var_kind, line: var_line, preview: var_preview);
  }

  @protected
  SearchRequest sse_decode_search_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roots = sse_decode_list_String(deserializer);
    var var_query = sse_decode_String(deserializer);
    var var_searchContent = sse_decode_bool(deserializer);
    var var_matchCase = sse_decode_bool(deserializer);
    var var_useWildcards = sse_decode_bool(deserializer);
    var var_maxResults = sse_decode_u_64(deserializer);
    var var_skipHidden = sse_decode_bool(deserializer);
    var var_excludedDirNames = sse_decode_list_String(deserializer);
    var var_allowedExtensions = sse_decode_opt_list_String(deserializer);
    return SearchRequest(
        roots: var_roots,
        query: var_query,
        searchContent: var_searchContent,
        matchCase: var_matchCase,
        useWildcards: var_useWildcards,
        maxResults: var_maxResults,
        skipHidden: var_skipHidden,
        excludedDirNames: var_excludedDirNames,
        allowedExtensions: var_allowedExtensions);
  }

  @protected
  SearchSummary sse_decode_search_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hits = sse_decode_list_search_hit(deserializer);
    var var_filesScanned = sse_decode_u_64(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return SearchSummary(
        hits: var_hits,
        filesScanned: var_filesScanned,
        truncated: var_truncated,
        cancelled: var_cancelled);
  }

  @protected
  SortField sse_decode_sort_field(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortField.values[inner];
  }

  @protected
  SortSpec sse_decode_sort_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field = sse_decode_sort_field(deserializer);
    var var_ascending = sse_decode_bool(deserializer);
    var var_dirsFirst = sse_decode_bool(deserializer);
    var var_includeHidden = sse_decode_bool(deserializer);
    return SortSpec(
        field: var_field,
        ascending: var_ascending,
        dirsFirst: var_dirsFirst,
        includeHidden: var_includeHidden);
  }

  @protected
  StatsEvent sse_decode_stats_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_quick_progress(deserializer);
        return StatsEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_folder_stats(deserializer);
        return StatsEvent_Done(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ThumbnailInfo sse_decode_thumbnail_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_fromCache = sse_decode_bool(deserializer);
    return ThumbnailInfo(
        path: var_path,
        width: var_width,
        height: var_height,
        fromCache: var_fromCache);
  }

  @protected
  TrashOutcome sse_decode_trash_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_trashed = sse_decode_list_String(deserializer);
    var var_failed = sse_decode_list_failed_item(deserializer);
    return TrashOutcome(trashed: var_trashed, failed: var_failed);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_op_event_Sse(
      RustStreamSink<OpEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_op_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_quick_event_Sse(
      RustStreamSink<QuickEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_quick_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_scan_event_Sse(
      RustStreamSink<ScanEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_scan_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_search_event_Sse(
      RustStreamSink<SearchEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_search_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_stats_event_Sse(
      RustStreamSink<StatsEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_stats_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_archive_entry(ArchiveEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_bool(self.isDir, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_folder_stats(
      FolderStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_folder_stats(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_op_outcome(
      OpOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_op_outcome(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_op_progress(
      OpProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_op_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_quick_outcome(
      QuickOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_quick_outcome(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_quick_progress(
      QuickProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_quick_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scan_progress(
      ScanProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scan_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scan_request(
      ScanRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scan_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_hit(
      SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_hit(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_request(
      SearchRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_search_summary(
      SearchSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_search_summary(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sort_spec(
      SortSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sort_spec(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_collision(Collision self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dir_entry_info(DirEntryInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDir, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_i_64(self.modifiedMs, serializer);
  }

  @protected
  void sse_encode_duplicate_group(
      DuplicateGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_list_dir_entry_info(self.files, serializer);
  }

  @protected
  void sse_encode_failed_item(FailedItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_folder_stats(FolderStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.files, serializer);
    sse_encode_u_64(self.dirs, serializer);
    sse_encode_u_64(self.bytes, serializer);
    sse_encode_String(self.largestPath, serializer);
    sse_encode_u_64(self.largestBytes, serializer);
    sse_encode_i_64(self.newestMs, serializer);
    sse_encode_u_64(self.unreadable, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_hit_kind(HitKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image_target(ImageTarget self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_transform(
      ImageTransform self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_archive_entry(
      List<ArchiveEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_archive_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dir_entry_info(
      List<DirEntryInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dir_entry_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_duplicate_group(
      List<DuplicateGroup> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_duplicate_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_failed_item(
      List<FailedItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_failed_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_hit(
      List<SearchHit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_op_event(OpEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case OpEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_op_progress(field0, serializer);
      case OpEvent_Done(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_op_outcome(field0, serializer);
    }
  }

  @protected
  void sse_encode_op_outcome(OpOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.completed, serializer);
    sse_encode_list_String(self.skipped, serializer);
    sse_encode_list_failed_item(self.failed, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_op_progress(OpProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.filesDone, serializer);
    sse_encode_u_64(self.filesTotal, serializer);
    sse_encode_u_64(self.bytesDone, serializer);
    sse_encode_u_64(self.bytesTotal, serializer);
    sse_encode_String(self.current, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_quick_event(QuickEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case QuickEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_quick_progress(field0, serializer);
      case QuickEvent_Done(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_quick_outcome(field0, serializer);
    }
  }

  @protected
  void sse_encode_quick_outcome(QuickOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.produced, serializer);
    sse_encode_list_failed_item(self.failed, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_quick_progress(QuickProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.filesDone, serializer);
    sse_encode_u_64(self.filesTotal, serializer);
    sse_encode_u_64(self.bytesDone, serializer);
    sse_encode_u_64(self.bytesTotal, serializer);
    sse_encode_String(self.current, serializer);
  }

  @protected
  void sse_encode_scan_event(ScanEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ScanEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_scan_progress(field0, serializer);
      case ScanEvent_Done(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_list_duplicate_group(field0, serializer);
    }
  }

  @protected
  void sse_encode_scan_phase(ScanPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scan_phase(self.phase, serializer);
    sse_encode_u_64(self.filesSeen, serializer);
    sse_encode_u_64(self.filesHashed, serializer);
    sse_encode_u_64(self.hashTotal, serializer);
    sse_encode_String(self.currentPath, serializer);
  }

  @protected
  void sse_encode_scan_request(ScanRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.roots, serializer);
    sse_encode_u_64(self.minSize, serializer);
    sse_encode_list_String(self.excludedDirNames, serializer);
    sse_encode_opt_list_String(self.allowedExtensions, serializer);
    sse_encode_bool(self.skipHidden, serializer);
    sse_encode_bool(self.skipBundles, serializer);
  }

  @protected
  void sse_encode_search_event(SearchEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SearchEvent_Hit(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_search_hit(field0, serializer);
      case SearchEvent_Done(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_search_summary(field0, serializer);
    }
  }

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dir_entry_info(self.entry, serializer);
    sse_encode_hit_kind(self.kind, serializer);
    sse_encode_opt_box_autoadd_u_64(self.line, serializer);
    sse_encode_opt_String(self.preview, serializer);
  }

  @protected
  void sse_encode_search_request(SearchRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.roots, serializer);
    sse_encode_String(self.query, serializer);
    sse_encode_bool(self.searchContent, serializer);
    sse_encode_bool(self.matchCase, serializer);
    sse_encode_bool(self.useWildcards, serializer);
    sse_encode_u_64(self.maxResults, serializer);
    sse_encode_bool(self.skipHidden, serializer);
    sse_encode_list_String(self.excludedDirNames, serializer);
    sse_encode_opt_list_String(self.allowedExtensions, serializer);
  }

  @protected
  void sse_encode_search_summary(SearchSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_search_hit(self.hits, serializer);
    sse_encode_u_64(self.filesScanned, serializer);
    sse_encode_bool(self.truncated, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_sort_field(SortField self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sort_spec(SortSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sort_field(self.field, serializer);
    sse_encode_bool(self.ascending, serializer);
    sse_encode_bool(self.dirsFirst, serializer);
    sse_encode_bool(self.includeHidden, serializer);
  }

  @protected
  void sse_encode_stats_event(StatsEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StatsEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_quick_progress(field0, serializer);
      case StatsEvent_Done(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_folder_stats(field0, serializer);
    }
  }

  @protected
  void sse_encode_thumbnail_info(ThumbnailInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_bool(self.fromCache, serializer);
  }

  @protected
  void sse_encode_trash_outcome(TrashOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.trashed, serializer);
    sse_encode_list_failed_item(self.failed, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
