// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ArchiveEntry {
  final String name;

  /// Uncompressed size in bytes.
  final BigInt size;
  final bool isDir;

  const ArchiveEntry({
    required this.name,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          isDir == other.isDir;
}
