// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'archive.dart';
import 'dedupe.dart';
import 'fileops.dart';
import 'listing.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'search.dart';
import 'thumbnail.dart';
import 'trash.dart';
part 'bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `begin`, `end`, `registry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Cancels the in-flight operation registered under `op_id`.
///
/// Returns false if nothing was registered — normal when the operation
/// finished between the user's click and this call arriving.
Future<bool> cancelOp({required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeCancelOp(opId: opId);

/// Streams a duplicate scan. Replaces the Dart isolate in
/// `duplicate_finder_service.dart`.
Stream<ScanEvent> scanDuplicatesStream(
        {required ScanRequest req, required String opId}) =>
    NotilusCore.instance.api
        .crateApiBridgeScanDuplicatesStream(req: req, opId: opId);

/// Files and bytes under `paths`, for sizing a progress bar before starting.
Future<Uint64List> measurePaths({required List<String> paths}) =>
    NotilusCore.instance.api.crateApiBridgeMeasurePaths(paths: paths);

/// Copies `sources` into `dest_dir`, streaming progress.
Stream<OpEvent> copyPathsStream(
        {required List<String> sources,
        required String destDir,
        required Collision collision,
        required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeCopyPathsStream(
        sources: sources, destDir: destDir, collision: collision, opId: opId);

/// Moves `sources` into `dest_dir`, streaming progress. Uses `rename(2)` where
/// possible and falls back to copy-then-delete across filesystems.
Stream<OpEvent> movePathsStream(
        {required List<String> sources,
        required String destDir,
        required Collision collision,
        required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeMovePathsStream(
        sources: sources, destDir: destDir, collision: collision, opId: opId);

Future<String> createFile({required String dir, required String name}) =>
    NotilusCore.instance.api.crateApiBridgeCreateFile(dir: dir, name: name);

Future<String> createDir({required String dir, required String name}) =>
    NotilusCore.instance.api.crateApiBridgeCreateDir(dir: dir, name: name);

Future<String> renamePath({required String path, required String newName}) =>
    NotilusCore.instance.api
        .crateApiBridgeRenamePath(path: path, newName: newName);

/// Moves everything to the platform recycle bin — a real Recycle Bin on
/// Windows and an XDG trash on Linux, where the Dart code used to hard-delete.
Future<TrashOutcome> moveToTrash({required List<String> paths}) =>
    NotilusCore.instance.api.crateApiBridgeMoveToTrash(paths: paths);

/// Permanently deletes. The UI must confirm before calling this.
Future<TrashOutcome> deletePermanently({required List<String> paths}) =>
    NotilusCore.instance.api.crateApiBridgeDeletePermanently(paths: paths);

/// Streams filename (and optionally content) matches as they are found.
Stream<SearchEvent> searchFilesStream(
        {required SearchRequest req, required String opId}) =>
    NotilusCore.instance.api
        .crateApiBridgeSearchFilesStream(req: req, opId: opId);

/// One directory, pre-sorted. Replaces `file_service.dart:listDirectory`.
Future<List<DirEntryInfo>> listDir(
        {required String path, required SortSpec sort}) =>
    NotilusCore.instance.api.crateApiBridgeListDir(path: path, sort: sort);

Future<String> hashFile({required String path}) =>
    NotilusCore.instance.api.crateApiBridgeHashFile(path: path);

Future<String> hashFilePrefix({required String path, required BigInt window}) =>
    NotilusCore.instance.api
        .crateApiBridgeHashFilePrefix(path: path, window: window);

/// Lists an archive's entries. For a zip this reads the central directory
/// only — no inflate, no loading the file into memory.
Future<List<ArchiveEntry>> listArchive({required String path}) =>
    NotilusCore.instance.api.crateApiBridgeListArchive(path: path);

Future<Uint8List> extractArchiveEntry(
        {required String path, required String entryName}) =>
    NotilusCore.instance.api
        .crateApiBridgeExtractArchiveEntry(path: path, entryName: entryName);

Future<ThumbnailInfo> thumbnailImage(
        {required String src, required String dst, required int maxDim}) =>
    NotilusCore.instance.api
        .crateApiBridgeThumbnailImage(src: src, dst: dst, maxDim: maxDim);

/// Stable cache filename for a thumbnail, matching the Dart FNV-1a scheme so
/// the existing on-disk cache stays valid.
Future<String> thumbnailCacheKey(
        {required String path,
        required PlatformInt64 modifiedMs,
        required BigInt size,
        required int dim}) =>
    NotilusCore.instance.api.crateApiBridgeThumbnailCacheKey(
        path: path, modifiedMs: modifiedMs, size: size, dim: dim);

@freezed
sealed class OpEvent with _$OpEvent {
  const OpEvent._();

  const factory OpEvent.progress(
    OpProgress field0,
  ) = OpEvent_Progress;
  const factory OpEvent.done(
    OpOutcome field0,
  ) = OpEvent_Done;
}

@freezed
sealed class ScanEvent with _$ScanEvent {
  const ScanEvent._();

  const factory ScanEvent.progress(
    ScanProgress field0,
  ) = ScanEvent_Progress;
  const factory ScanEvent.done(
    List<DuplicateGroup> field0,
  ) = ScanEvent_Done;
}

@freezed
sealed class SearchEvent with _$SearchEvent {
  const SearchEvent._();

  const factory SearchEvent.hit(
    SearchHit field0,
  ) = SearchEvent_Hit;
  const factory SearchEvent.done(
    SearchSummary field0,
  ) = SearchEvent_Done;
}
