// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'archive.dart';
import 'dedupe.dart';
import 'email.dart';
import 'fileops.dart';
import 'listing.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'quick.dart';
import 'search.dart';
import 'sharing.dart';
import 'thumbnail.dart';
import 'trash.dart';
part 'bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `begin`, `end`, `registry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Cancels the in-flight operation registered under `op_id`.
///
/// Returns false if nothing was registered — normal when the operation
/// finished between the user's click and this call arriving.
Future<bool> cancelOp({required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeCancelOp(opId: opId);

/// Streams a duplicate scan. Replaces the Dart isolate in
/// `duplicate_finder_service.dart`.
Stream<ScanEvent> scanDuplicatesStream(
        {required ScanRequest req, required String opId}) =>
    NotilusCore.instance.api
        .crateApiBridgeScanDuplicatesStream(req: req, opId: opId);

/// Files and bytes under `paths`, for sizing a progress bar before starting.
Future<Uint64List> measurePaths({required List<String> paths}) =>
    NotilusCore.instance.api.crateApiBridgeMeasurePaths(paths: paths);

/// Copies `sources` into `dest_dir`, streaming progress.
Stream<OpEvent> copyPathsStream(
        {required List<String> sources,
        required String destDir,
        required Collision collision,
        required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeCopyPathsStream(
        sources: sources, destDir: destDir, collision: collision, opId: opId);

/// Moves `sources` into `dest_dir`, streaming progress. Uses `rename(2)` where
/// possible and falls back to copy-then-delete across filesystems.
Stream<OpEvent> movePathsStream(
        {required List<String> sources,
        required String destDir,
        required Collision collision,
        required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeMovePathsStream(
        sources: sources, destDir: destDir, collision: collision, opId: opId);

Future<String> createFile({required String dir, required String name}) =>
    NotilusCore.instance.api.crateApiBridgeCreateFile(dir: dir, name: name);

Future<String> createDir({required String dir, required String name}) =>
    NotilusCore.instance.api.crateApiBridgeCreateDir(dir: dir, name: name);

Future<String> renamePath({required String path, required String newName}) =>
    NotilusCore.instance.api
        .crateApiBridgeRenamePath(path: path, newName: newName);

/// Moves everything to the platform recycle bin — a real Recycle Bin on
/// Windows and an XDG trash on Linux, where the Dart code used to hard-delete.
Future<TrashOutcome> moveToTrash({required List<String> paths}) =>
    NotilusCore.instance.api.crateApiBridgeMoveToTrash(paths: paths);

/// Permanently deletes. The UI must confirm before calling this.
Future<TrashOutcome> deletePermanently({required List<String> paths}) =>
    NotilusCore.instance.api.crateApiBridgeDeletePermanently(paths: paths);

/// Zips `sources` into `dest_dir/archive_name`, streaming progress.
Stream<QuickEvent> compressPathsStream(
        {required List<String> sources,
        required String destDir,
        required String archiveName,
        required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeCompressPathsStream(
        sources: sources,
        destDir: destDir,
        archiveName: archiveName,
        opId: opId);

/// Unpacks an archive into `dest_dir`, streaming progress. With
/// `into_subfolder` the contents land in a new folder named after the archive.
Stream<QuickEvent> extractArchiveStream(
        {required String path,
        required String destDir,
        required bool intoSubfolder,
        required String opId}) =>
    NotilusCore.instance.api.crateApiBridgeExtractArchiveStream(
        path: path, destDir: destDir, intoSubfolder: intoSubfolder, opId: opId);

/// Walks a folder and reports what it actually holds. Cancellable, because a
/// home directory can take a while and the user may change their mind.
Stream<StatsEvent> folderStatsStream(
        {required String path, required String opId}) =>
    NotilusCore.instance.api
        .crateApiBridgeFolderStatsStream(path: path, opId: opId);

/// Re-encodes an image into `dest_dir`, optionally fitting it inside a
/// `max_dim` box. Returns the path written. The original is left alone.
Future<String> convertImage(
        {required String src,
        required String destDir,
        required ImageTarget format,
        int? maxDim,
        required int quality}) =>
    NotilusCore.instance.api.crateApiBridgeConvertImage(
        src: src,
        destDir: destDir,
        format: format,
        maxDim: maxDim,
        quality: quality);

/// Rotates or flips an image, in place or into a suffixed sibling. Returns the
/// path written.
Future<String> transformImage(
        {required String src,
        required ImageTransform transform,
        required bool inPlace}) =>
    NotilusCore.instance.api.crateApiBridgeTransformImage(
        src: src, transform: transform, inPlace: inPlace);

/// Streams filename (and optionally content) matches as they are found.
Stream<SearchEvent> searchFilesStream(
        {required SearchRequest req, required String opId}) =>
    NotilusCore.instance.api
        .crateApiBridgeSearchFilesStream(req: req, opId: opId);

/// One directory, pre-sorted. Replaces `file_service.dart:listDirectory`.
Future<List<DirEntryInfo>> listDir(
        {required String path, required SortSpec sort}) =>
    NotilusCore.instance.api.crateApiBridgeListDir(path: path, sort: sort);

Future<String> hashFile({required String path}) =>
    NotilusCore.instance.api.crateApiBridgeHashFile(path: path);

Future<String> hashFilePrefix({required String path, required BigInt window}) =>
    NotilusCore.instance.api
        .crateApiBridgeHashFilePrefix(path: path, window: window);

/// Lists an archive's entries. For a zip this reads the central directory
/// only — no inflate, no loading the file into memory.
Future<List<ArchiveEntry>> listArchive({required String path}) =>
    NotilusCore.instance.api.crateApiBridgeListArchive(path: path);

Future<Uint8List> extractArchiveEntry(
        {required String path, required String entryName}) =>
    NotilusCore.instance.api
        .crateApiBridgeExtractArchiveEntry(path: path, entryName: entryName);

Future<ThumbnailInfo> thumbnailImage(
        {required String src, required String dst, required int maxDim}) =>
    NotilusCore.instance.api
        .crateApiBridgeThumbnailImage(src: src, dst: dst, maxDim: maxDim);

/// Stable cache filename for a thumbnail, matching the Dart FNV-1a scheme so
/// the existing on-disk cache stays valid.
Future<String> thumbnailCacheKey(
        {required String path,
        required PlatformInt64 modifiedMs,
        required BigInt size,
        required int dim}) =>
    NotilusCore.instance.api.crateApiBridgeThumbnailCacheKey(
        path: path, modifiedMs: modifiedMs, size: size, dim: dim);

/// Parses a `.eml` or `.msg` into headers, bodies and an attachment list.
///
/// The attachments come back as descriptions only. Their bytes are fetched one
/// at a time through [`read_email_attachment_bytes`], so opening a message with
/// a 40 MB deck in it doesn't move 40 MB into Dart before anything is shown.
Future<EmailMessageInfo> readEmailMessage({required String path}) =>
    NotilusCore.instance.api.crateApiBridgeReadEmailMessage(path: path);

/// The bytes of one attachment, addressed by its index in the parsed message.
Future<EmailAttachmentData> readEmailAttachmentBytes(
        {required String path, required int index}) =>
    NotilusCore.instance.api
        .crateApiBridgeReadEmailAttachmentBytes(path: path, index: index);

/// Writes one attachment into `dest_dir`, returning the path it was given.
Future<String> saveEmailAttachmentTo(
        {required String path, required int index, required String destDir}) =>
    NotilusCore.instance.api.crateApiBridgeSaveEmailAttachmentTo(
        path: path, index: index, destDir: destDir);

/// Starts the SMB server and streams what it does.
///
/// The sink is held for the server's lifetime, so the Dart stream stays open
/// until [`smb_server_stop`] — closing it early would leave the UI blind to
/// clients connecting.
Stream<SmbServerEvent> smbServerStart({required SmbServerSettings settings}) =>
    NotilusCore.instance.api.crateApiBridgeSmbServerStart(settings: settings);

/// Stops the server. False when nothing was running.
Future<bool> smbServerStop() =>
    NotilusCore.instance.api.crateApiBridgeSmbServerStop();

Future<SmbServerStatus> smbServerStatus() =>
    NotilusCore.instance.api.crateApiBridgeSmbServerStatus();

/// Opens a session against a share and keeps it for later calls.
Future<SmbSession> smbClientConnect({required SmbClientSettings settings}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientConnect(settings: settings);

/// Checks credentials without keeping a session, returning the dialect that
/// was negotiated.
Future<String> smbClientProbe({required SmbClientSettings settings}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientProbe(settings: settings);

Future<bool> smbClientDisconnect({required String sessionId}) =>
    NotilusCore.instance.api
        .crateApiBridgeSmbClientDisconnect(sessionId: sessionId);

Future<List<SmbEntry>> smbClientList(
        {required String sessionId, required String path}) =>
    NotilusCore.instance.api
        .crateApiBridgeSmbClientList(sessionId: sessionId, path: path);

Future<SmbEntry?> smbClientStat(
        {required String sessionId, required String path}) =>
    NotilusCore.instance.api
        .crateApiBridgeSmbClientStat(sessionId: sessionId, path: path);

/// Opens a file for reading or writing, returning a handle scoped to the
/// session.
Future<SmbOpenFile> smbClientOpen(
        {required String sessionId,
        required String path,
        required bool write,
        required bool truncate}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientOpen(
        sessionId: sessionId, path: path, write: write, truncate: truncate);

/// Reads at most `length` bytes. An empty result means end of file.
Future<Uint8List> smbClientRead(
        {required String sessionId,
        required BigInt handle,
        required BigInt offset,
        required int length}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientRead(
        sessionId: sessionId, handle: handle, offset: offset, length: length);

/// Writes at `offset`, returning how many bytes the server accepted — which
/// may be fewer than were offered.
Future<int> smbClientWrite(
        {required String sessionId,
        required BigInt handle,
        required BigInt offset,
        required List<int> data}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientWrite(
        sessionId: sessionId, handle: handle, offset: offset, data: data);

Future<void> smbClientClose(
        {required String sessionId, required BigInt handle}) =>
    NotilusCore.instance.api
        .crateApiBridgeSmbClientClose(sessionId: sessionId, handle: handle);

Future<void> smbClientCreateDirectory(
        {required String sessionId, required String path}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientCreateDirectory(
        sessionId: sessionId, path: path);

Future<void> smbClientDelete(
        {required String sessionId,
        required String path,
        required bool isDir}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientDelete(
        sessionId: sessionId, path: path, isDir: isDir);

Future<void> smbClientRename(
        {required String sessionId,
        required String from,
        required String to,
        required bool replace}) =>
    NotilusCore.instance.api.crateApiBridgeSmbClientRename(
        sessionId: sessionId, from: from, to: to, replace: replace);

/// Copies a file inside one share, server-side where the server supports it.
Future<BigInt> smbClientCopy(
        {required String sessionId,
        required String from,
        required String to}) =>
    NotilusCore.instance.api
        .crateApiBridgeSmbClientCopy(sessionId: sessionId, from: from, to: to);

@freezed
sealed class OpEvent with _$OpEvent {
  const OpEvent._();

  const factory OpEvent.progress(
    OpProgress field0,
  ) = OpEvent_Progress;
  const factory OpEvent.done(
    OpOutcome field0,
  ) = OpEvent_Done;
}

@freezed
sealed class QuickEvent with _$QuickEvent {
  const QuickEvent._();

  const factory QuickEvent.progress(
    QuickProgress field0,
  ) = QuickEvent_Progress;
  const factory QuickEvent.done(
    QuickOutcome field0,
  ) = QuickEvent_Done;
}

@freezed
sealed class ScanEvent with _$ScanEvent {
  const ScanEvent._();

  const factory ScanEvent.progress(
    ScanProgress field0,
  ) = ScanEvent_Progress;
  const factory ScanEvent.done(
    List<DuplicateGroup> field0,
  ) = ScanEvent_Done;
}

@freezed
sealed class SearchEvent with _$SearchEvent {
  const SearchEvent._();

  const factory SearchEvent.hit(
    SearchHit field0,
  ) = SearchEvent_Hit;
  const factory SearchEvent.done(
    SearchSummary field0,
  ) = SearchEvent_Done;
}

@freezed
sealed class StatsEvent with _$StatsEvent {
  const StatsEvent._();

  const factory StatsEvent.progress(
    QuickProgress field0,
  ) = StatsEvent_Progress;
  const factory StatsEvent.done(
    FolderStats field0,
  ) = StatsEvent_Done;
}
