// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'listing.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A set of files with identical size and content hash — byte-for-byte
/// duplicates. Mirrors Dart's `DuplicateGroup`.
class DuplicateGroup {
  final String hash;
  final BigInt size;
  final List<DirEntryInfo> files;

  const DuplicateGroup({
    required this.hash,
    required this.size,
    required this.files,
  });

  @override
  int get hashCode => hash.hashCode ^ size.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DuplicateGroup &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          size == other.size &&
          files == other.files;
}

enum ScanPhase {
  /// Walking the tree.
  scanning,

  /// Fingerprinting and hashing size collisions.
  comparing,
  ;
}

class ScanProgress {
  final ScanPhase phase;
  final BigInt filesSeen;
  final BigInt filesHashed;
  final BigInt hashTotal;
  final String currentPath;

  const ScanProgress({
    required this.phase,
    required this.filesSeen,
    required this.filesHashed,
    required this.hashTotal,
    required this.currentPath,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      filesSeen.hashCode ^
      filesHashed.hashCode ^
      hashTotal.hashCode ^
      currentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          filesSeen == other.filesSeen &&
          filesHashed == other.filesHashed &&
          hashTotal == other.hashTotal &&
          currentPath == other.currentPath;
}

class ScanRequest {
  final List<String> roots;

  /// Files smaller than this are ignored entirely.
  final BigInt minSize;

  /// Lowercase directory basenames to prune.
  final List<String> excludedDirNames;

  /// Lowercase extensions including the leading dot. `None` means every file.
  final List<String>? allowedExtensions;
  final bool skipHidden;
  final bool skipBundles;

  const ScanRequest({
    required this.roots,
    required this.minSize,
    required this.excludedDirNames,
    this.allowedExtensions,
    required this.skipHidden,
    required this.skipBundles,
  });

  @override
  int get hashCode =>
      roots.hashCode ^
      minSize.hashCode ^
      excludedDirNames.hashCode ^
      allowedExtensions.hashCode ^
      skipHidden.hashCode ^
      skipBundles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRequest &&
          runtimeType == other.runtimeType &&
          roots == other.roots &&
          minSize == other.minSize &&
          excludedDirNames == other.excludedDirNames &&
          allowedExtensions == other.allowedExtensions &&
          skipHidden == other.skipHidden &&
          skipBundles == other.skipBundles;
}
