// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EmailAddressInfo {
  final String name;
  final String email;

  const EmailAddressInfo({
    required this.name,
    required this.email,
  });

  @override
  int get hashCode => name.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailAddressInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          email == other.email;
}

/// One attachment's bytes, for rendering inline or handing to the OS.
class EmailAttachmentData {
  final String name;
  final String mime;
  final Uint8List bytes;

  const EmailAttachmentData({
    required this.name,
    required this.mime,
    required this.bytes,
  });

  @override
  int get hashCode => name.hashCode ^ mime.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailAttachmentData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mime == other.mime &&
          bytes == other.bytes;
}

class EmailAttachmentInfo {
  final int index;
  final String name;
  final String mime;
  final BigInt size;
  final String contentId;
  final bool isInline;

  const EmailAttachmentInfo({
    required this.index,
    required this.name,
    required this.mime,
    required this.size,
    required this.contentId,
    required this.isInline,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      name.hashCode ^
      mime.hashCode ^
      size.hashCode ^
      contentId.hashCode ^
      isInline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailAttachmentInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          mime == other.mime &&
          size == other.size &&
          contentId == other.contentId &&
          isInline == other.isInline;
}

class EmailHeaderInfo {
  final String name;
  final String value;

  const EmailHeaderInfo({
    required this.name,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailHeaderInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class EmailMessageInfo {
  final String subject;
  final List<EmailAddressInfo> from;
  final List<EmailAddressInfo> to;
  final List<EmailAddressInfo> cc;
  final List<EmailAddressInfo> bcc;
  final List<EmailAddressInfo> replyTo;
  final String date;

  /// Milliseconds since the epoch, or 0 when the message carried no date.
  final PlatformInt64 dateEpochMs;
  final String messageId;
  final String bodyText;
  final String bodyHtml;
  final List<EmailHeaderInfo> headers;
  final List<EmailAttachmentInfo> attachments;

  /// `"eml"` or `"msg"`.
  final String format;

  const EmailMessageInfo({
    required this.subject,
    required this.from,
    required this.to,
    required this.cc,
    required this.bcc,
    required this.replyTo,
    required this.date,
    required this.dateEpochMs,
    required this.messageId,
    required this.bodyText,
    required this.bodyHtml,
    required this.headers,
    required this.attachments,
    required this.format,
  });

  @override
  int get hashCode =>
      subject.hashCode ^
      from.hashCode ^
      to.hashCode ^
      cc.hashCode ^
      bcc.hashCode ^
      replyTo.hashCode ^
      date.hashCode ^
      dateEpochMs.hashCode ^
      messageId.hashCode ^
      bodyText.hashCode ^
      bodyHtml.hashCode ^
      headers.hashCode ^
      attachments.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmailMessageInfo &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          from == other.from &&
          to == other.to &&
          cc == other.cc &&
          bcc == other.bcc &&
          replyTo == other.replyTo &&
          date == other.date &&
          dateEpochMs == other.dateEpochMs &&
          messageId == other.messageId &&
          bodyText == other.bodyText &&
          bodyHtml == other.bodyHtml &&
          headers == other.headers &&
          attachments == other.attachments &&
          format == other.format;
}
