// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What to do when the destination name is already taken.
enum Collision {
  /// Finder-style " copy", " copy 2"… Never destroys anything.
  rename,

  /// Replace the existing item.
  overwrite,

  /// Leave the existing item alone and report the source as skipped.
  skip,
  ;
}

class FailedItem {
  final String path;
  final String error;

  const FailedItem({
    required this.path,
    required this.error,
  });

  @override
  int get hashCode => path.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FailedItem &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          error == other.error;
}

class OpOutcome {
  /// Destination paths that were successfully created.
  final List<String> completed;

  /// Sources deliberately left alone under [`Collision::Skip`].
  final List<String> skipped;
  final List<FailedItem> failed;
  final bool cancelled;

  const OpOutcome({
    required this.completed,
    required this.skipped,
    required this.failed,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      completed.hashCode ^
      skipped.hashCode ^
      failed.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpOutcome &&
          runtimeType == other.runtimeType &&
          completed == other.completed &&
          skipped == other.skipped &&
          failed == other.failed &&
          cancelled == other.cancelled;
}

class OpProgress {
  final BigInt filesDone;
  final BigInt filesTotal;
  final BigInt bytesDone;
  final BigInt bytesTotal;

  /// Path currently being worked on.
  final String current;

  const OpProgress({
    required this.filesDone,
    required this.filesTotal,
    required this.bytesDone,
    required this.bytesTotal,
    required this.current,
  });

  @override
  int get hashCode =>
      filesDone.hashCode ^
      filesTotal.hashCode ^
      bytesDone.hashCode ^
      bytesTotal.hashCode ^
      current.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpProgress &&
          runtimeType == other.runtimeType &&
          filesDone == other.filesDone &&
          filesTotal == other.filesTotal &&
          bytesDone == other.bytesDone &&
          bytesTotal == other.bytesTotal &&
          current == other.current;
}
