// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One filesystem entry. Mirrors Dart's `FileEntry`.
class DirEntryInfo {
  final String path;
  final String name;
  final bool isDir;
  final BigInt size;

  /// Milliseconds since the Unix epoch; negative for pre-1970 timestamps.
  final PlatformInt64 modifiedMs;

  const DirEntryInfo({
    required this.path,
    required this.name,
    required this.isDir,
    required this.size,
    required this.modifiedMs,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      modifiedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirEntryInfo &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedMs == other.modifiedMs;
}

enum SortField {
  name,
  kind,
  modified,
  size,
  ;
}

class SortSpec {
  final SortField field;
  final bool ascending;

  /// Keep directories above files regardless of the active field — the
  /// Finder behaviour the Dart comparator hard-codes.
  final bool dirsFirst;

  /// Include dot-prefixed entries. Dart's listing always hides them.
  final bool includeHidden;

  const SortSpec({
    required this.field,
    required this.ascending,
    required this.dirsFirst,
    required this.includeHidden,
  });

  @override
  int get hashCode =>
      field.hashCode ^
      ascending.hashCode ^
      dirsFirst.hashCode ^
      includeHidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SortSpec &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          ascending == other.ascending &&
          dirsFirst == other.dirsFirst &&
          includeHidden == other.includeHidden;
}
