// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'fileops.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What a folder actually contains, recursively.
class FolderStats {
  final String path;
  final BigInt files;
  final BigInt dirs;

  /// Apparent size: the sum of file lengths, not blocks on disk.
  final BigInt bytes;

  /// The single biggest file under `path`, which is almost always the answer
  /// to the question that prompted the user to ask for the size at all.
  final String largestPath;
  final BigInt largestBytes;

  /// Most recent mtime anywhere in the tree, in Unix milliseconds.
  final PlatformInt64 newestMs;

  /// Entries that couldn't be read — usually permissions. Reported rather
  /// than hidden, because they make the total an undercount.
  final BigInt unreadable;
  final bool cancelled;

  const FolderStats({
    required this.path,
    required this.files,
    required this.dirs,
    required this.bytes,
    required this.largestPath,
    required this.largestBytes,
    required this.newestMs,
    required this.unreadable,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      files.hashCode ^
      dirs.hashCode ^
      bytes.hashCode ^
      largestPath.hashCode ^
      largestBytes.hashCode ^
      newestMs.hashCode ^
      unreadable.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderStats &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          files == other.files &&
          dirs == other.dirs &&
          bytes == other.bytes &&
          largestPath == other.largestPath &&
          largestBytes == other.largestBytes &&
          newestMs == other.newestMs &&
          unreadable == other.unreadable &&
          cancelled == other.cancelled;
}

/// The formats a Quick Action can write. Deliberately three: PNG for lossless,
/// JPEG for photos, WebP for the web. The `image` crate writes WebP losslessly
/// only, which is fine for the "make this shareable" job and honest about it.
enum ImageTarget {
  png,
  jpeg,
  webP,
  ;
}

/// A lossless, one-click reorientation.
enum ImageTransform {
  rotateLeft,
  rotateRight,
  rotate180,
  flipHorizontal,
  flipVertical,
  ;
}

/// How a Quick Action ended.
class QuickOutcome {
  /// What was created — the archive path, the extraction root, the converted
  /// image. The UI selects `produced[0]` so the result is visible on return.
  final List<String> produced;

  /// Items that couldn't be handled. A single unreadable file never aborts
  /// the whole action; it lands here and the rest continues.
  final List<FailedItem> failed;
  final bool cancelled;

  const QuickOutcome({
    required this.produced,
    required this.failed,
    required this.cancelled,
  });

  @override
  int get hashCode => produced.hashCode ^ failed.hashCode ^ cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickOutcome &&
          runtimeType == other.runtimeType &&
          produced == other.produced &&
          failed == other.failed &&
          cancelled == other.cancelled;
}

/// Progress for any streaming Quick Action.
///
/// Deliberately the same shape as `fileops::OpProgress`: the UI already has a
/// progress bar bound to those fields, and a second, subtly different struct
/// would mean a second bar. `*_total` is 0 when the total isn't knowable up
/// front — a tar has to be read to be counted — which the UI shows as an
/// indeterminate bar.
class QuickProgress {
  final BigInt filesDone;
  final BigInt filesTotal;
  final BigInt bytesDone;
  final BigInt bytesTotal;

  /// The item being worked on, for the label under the bar.
  final String current;

  const QuickProgress({
    required this.filesDone,
    required this.filesTotal,
    required this.bytesDone,
    required this.bytesTotal,
    required this.current,
  });

  @override
  int get hashCode =>
      filesDone.hashCode ^
      filesTotal.hashCode ^
      bytesDone.hashCode ^
      bytesTotal.hashCode ^
      current.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickProgress &&
          runtimeType == other.runtimeType &&
          filesDone == other.filesDone &&
          filesTotal == other.filesTotal &&
          bytesDone == other.bytesDone &&
          bytesTotal == other.bytesTotal &&
          current == other.current;
}
