// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'listing.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum HitKind {
  name,
  content,
  ;
}

class SearchHit {
  final DirEntryInfo entry;
  final HitKind kind;

  /// 1-based line number, for content hits.
  final BigInt? line;

  /// A trimmed excerpt around the match, for content hits.
  final String? preview;

  const SearchHit({
    required this.entry,
    required this.kind,
    this.line,
    this.preview,
  });

  @override
  int get hashCode =>
      entry.hashCode ^ kind.hashCode ^ line.hashCode ^ preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          kind == other.kind &&
          line == other.line &&
          preview == other.preview;
}

class SearchRequest {
  final List<String> roots;

  /// What to look for. Empty means "match every file", which is how a
  /// filter-by-extension-only search is expressed.
  final String query;

  /// Match `query` against file *contents* as well as names.
  final bool searchContent;
  final bool matchCase;

  /// Treat `*` in `query` as a wildcard when matching names.
  final bool useWildcards;

  /// Stop after this many hits. 0 means unlimited.
  final BigInt maxResults;
  final bool skipHidden;

  /// Lowercase directory basenames to prune.
  final List<String> excludedDirNames;

  /// Lowercase extensions including the dot. `None` means every file.
  final List<String>? allowedExtensions;

  const SearchRequest({
    required this.roots,
    required this.query,
    required this.searchContent,
    required this.matchCase,
    required this.useWildcards,
    required this.maxResults,
    required this.skipHidden,
    required this.excludedDirNames,
    this.allowedExtensions,
  });

  @override
  int get hashCode =>
      roots.hashCode ^
      query.hashCode ^
      searchContent.hashCode ^
      matchCase.hashCode ^
      useWildcards.hashCode ^
      maxResults.hashCode ^
      skipHidden.hashCode ^
      excludedDirNames.hashCode ^
      allowedExtensions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchRequest &&
          runtimeType == other.runtimeType &&
          roots == other.roots &&
          query == other.query &&
          searchContent == other.searchContent &&
          matchCase == other.matchCase &&
          useWildcards == other.useWildcards &&
          maxResults == other.maxResults &&
          skipHidden == other.skipHidden &&
          excludedDirNames == other.excludedDirNames &&
          allowedExtensions == other.allowedExtensions;
}

class SearchSummary {
  final List<SearchHit> hits;
  final BigInt filesScanned;

  /// True if the run stopped early because `max_results` was reached.
  final bool truncated;
  final bool cancelled;

  const SearchSummary({
    required this.hits,
    required this.filesScanned,
    required this.truncated,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      hits.hashCode ^
      filesScanned.hashCode ^
      truncated.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchSummary &&
          runtimeType == other.runtimeType &&
          hits == other.hits &&
          filesScanned == other.filesScanned &&
          truncated == other.truncated &&
          cancelled == other.cancelled;
}
