// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sharing.freezed.dart';

class SmbClientSettings {
  final String host;
  final int port;
  final String share;
  final String username;
  final String domain;
  final String password;

  const SmbClientSettings({
    required this.host,
    required this.port,
    required this.share,
    required this.username,
    required this.domain,
    required this.password,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      share.hashCode ^
      username.hashCode ^
      domain.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbClientSettings &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          share == other.share &&
          username == other.username &&
          domain == other.domain &&
          password == other.password;
}

class SmbConnectionEvent {
  final BigInt connection;
  final String peer;
  final String user;

  /// The dialect for an authentication, the reason for a rejection, empty
  /// otherwise.
  final String detail;

  const SmbConnectionEvent({
    required this.connection,
    required this.peer,
    required this.user,
    required this.detail,
  });

  @override
  int get hashCode =>
      connection.hashCode ^ peer.hashCode ^ user.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbConnectionEvent &&
          runtimeType == other.runtimeType &&
          connection == other.connection &&
          peer == other.peer &&
          user == other.user &&
          detail == other.detail;
}

/// One entry in a remote listing.
class SmbEntry {
  final String name;
  final bool isDir;
  final BigInt size;

  /// Milliseconds since the epoch; 0 when the server reported none.
  final PlatformInt64 modifiedMs;
  final PlatformInt64 createdMs;
  final bool isHidden;
  final bool isReadOnly;

  const SmbEntry({
    required this.name,
    required this.isDir,
    required this.size,
    required this.modifiedMs,
    required this.createdMs,
    required this.isHidden,
    required this.isReadOnly,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      modifiedMs.hashCode ^
      createdMs.hashCode ^
      isHidden.hashCode ^
      isReadOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir &&
          size == other.size &&
          modifiedMs == other.modifiedMs &&
          createdMs == other.createdMs &&
          isHidden == other.isHidden &&
          isReadOnly == other.isReadOnly;
}

class SmbOpenFile {
  final BigInt handle;
  final BigInt size;

  const SmbOpenFile({
    required this.handle,
    required this.size,
  });

  @override
  int get hashCode => handle.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbOpenFile &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          size == other.size;
}

@freezed
sealed class SmbServerEvent with _$SmbServerEvent {
  const SmbServerEvent._();

  const factory SmbServerEvent.started(
    int field0,
  ) = SmbServerEvent_Started;
  const factory SmbServerEvent.stopped() = SmbServerEvent_Stopped;
  const factory SmbServerEvent.connected(
    SmbConnectionEvent field0,
  ) = SmbServerEvent_Connected;
  const factory SmbServerEvent.authenticated(
    SmbConnectionEvent field0,
  ) = SmbServerEvent_Authenticated;
  const factory SmbServerEvent.rejected(
    SmbConnectionEvent field0,
  ) = SmbServerEvent_Rejected;
  const factory SmbServerEvent.disconnected(
    SmbConnectionEvent field0,
  ) = SmbServerEvent_Disconnected;
  const factory SmbServerEvent.transfer(
    SmbTransferEvent field0,
  ) = SmbServerEvent_Transfer;
}

class SmbServerSettings {
  /// Address to listen on. `0.0.0.0` for the whole network, `127.0.0.1` to
  /// keep the share on this machine.
  final String bind;

  /// 0 asks the OS for a free port. 445 — the port other operating systems
  /// look for — needs administrator rights on every platform.
  final int port;
  final String serverName;
  final String workgroup;
  final List<SmbShareConfig> shares;
  final List<SmbUserConfig> users;
  final bool requireSigning;
  final int maxConnections;

  const SmbServerSettings({
    required this.bind,
    required this.port,
    required this.serverName,
    required this.workgroup,
    required this.shares,
    required this.users,
    required this.requireSigning,
    required this.maxConnections,
  });

  @override
  int get hashCode =>
      bind.hashCode ^
      port.hashCode ^
      serverName.hashCode ^
      workgroup.hashCode ^
      shares.hashCode ^
      users.hashCode ^
      requireSigning.hashCode ^
      maxConnections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbServerSettings &&
          runtimeType == other.runtimeType &&
          bind == other.bind &&
          port == other.port &&
          serverName == other.serverName &&
          workgroup == other.workgroup &&
          shares == other.shares &&
          users == other.users &&
          requireSigning == other.requireSigning &&
          maxConnections == other.maxConnections;
}

class SmbServerStatus {
  final bool running;
  final int port;
  final int connections;

  const SmbServerStatus({
    required this.running,
    required this.port,
    required this.connections,
  });

  @override
  int get hashCode => running.hashCode ^ port.hashCode ^ connections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbServerStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          port == other.port &&
          connections == other.connections;
}

class SmbSession {
  final String id;

  /// e.g. `SMB 3.1.1` — shown so a user can see what was negotiated.
  final String dialect;

  const SmbSession({
    required this.id,
    required this.dialect,
  });

  @override
  int get hashCode => id.hashCode ^ dialect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          dialect == other.dialect;
}

/// One folder to publish.
class SmbShareConfig {
  final String name;
  final String path;
  final bool readOnly;
  final String comment;

  /// Accounts allowed to attach. Empty means every account that can sign in,
  /// which is what a one-person setup wants.
  final List<String> allowedUsers;

  /// Whether someone with no account may attach. A guest is never granted
  /// write access, whatever `read_only` says.
  final bool guestOk;

  const SmbShareConfig({
    required this.name,
    required this.path,
    required this.readOnly,
    required this.comment,
    required this.allowedUsers,
    required this.guestOk,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      readOnly.hashCode ^
      comment.hashCode ^
      allowedUsers.hashCode ^
      guestOk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbShareConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          readOnly == other.readOnly &&
          comment == other.comment &&
          allowedUsers == other.allowedUsers &&
          guestOk == other.guestOk;
}

class SmbTransferEvent {
  final BigInt connection;
  final String share;
  final String path;

  /// True when the client was downloading from the share.
  final bool outbound;
  final BigInt bytes;

  const SmbTransferEvent({
    required this.connection,
    required this.share,
    required this.path,
    required this.outbound,
    required this.bytes,
  });

  @override
  int get hashCode =>
      connection.hashCode ^
      share.hashCode ^
      path.hashCode ^
      outbound.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbTransferEvent &&
          runtimeType == other.runtimeType &&
          connection == other.connection &&
          share == other.share &&
          path == other.path &&
          outbound == other.outbound &&
          bytes == other.bytes;
}

/// One account allowed to connect.
///
/// The password crosses the bridge once, at start, and is immediately reduced
/// to the hash the protocol needs; the running server never holds it.
class SmbUserConfig {
  final String username;
  final String password;

  const SmbUserConfig({
    required this.username,
    required this.password,
  });

  @override
  int get hashCode => username.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbUserConfig &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          password == other.password;
}
