// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'fileops.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TrashOutcome {
  /// Paths successfully moved to the recycle bin.
  final List<String> trashed;
  final List<FailedItem> failed;

  const TrashOutcome({
    required this.trashed,
    required this.failed,
  });

  @override
  int get hashCode => trashed.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrashOutcome &&
          runtimeType == other.runtimeType &&
          trashed == other.trashed &&
          failed == other.failed;
}
